#!/bin/sh

bookmark="$(xclip -o)"
file="$HOME/.local/share/bookmarks/snippets"

if grep -q "^$bookmark$" "$file"; then
        notify-send "Already bookmarked!"
else
        notify-send "Bookmark added!" "$bookmark is now saved to the file"
        echo "$bookmark" >> "$file"
fi
